export const AlertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const AuthConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT'
};

export const RestaurantAPIConstants = {
  FETCH_RESTAURANT_REQUEST: 'FETCH_RESTAURANT_REQUEST',
  FETCH_RESTAURANT_SUCCESS: 'FETCH_RESTAURANT_SUCCESS',
  FETCH_RESTAURANT_FAILURE: 'FETCH_RESTAURANT_FAILURE',
  FETCH_SINGLE_RESTAURANT_SUCCESS: 'FETCH_SINGLE_RESTAURANT_SUCCESS',
  FETCH_SINGLE_RESTAURANT_FAILURE: 'FETCH_SINGLE_RESTAURANT_FAILURE'
};