FROM node:carbon
# Create app directory
WORKDIR /usr/src/app
# Bundle app source
COPY . .
# npm install
RUN  npm install --quiet
# Run npm install --global grpc --unsafe-perm
EXPOSE 3000 9207
CMD [ "npm", "run", "start" ]